### ISSUE TITLE
Workmanager without activity

### ISSUE THREAD

**Issue by kiransnagaraj** [krunalpatel3/WorkManager-Example-Andorid#2]
Hi Krunalpatel I tried to run workmanager without activity. From application instance I tried to run workmanager but it's nit happening.  Please suggest better way to achieve this issue.
Thanks in advance

**Comment by krunalpatel3** [comment]
means you want to start workmanager without launching acitvity?

**Comment by krunalpatel3** [comment]
so you want to start workmanager on Application start.

**Comment by kiransnagaraj** [comment]
Hi Krunal.

Thanks for helping me out.
Actually I have to do background work without ui. I thought of using
workmanager. I just found one solution like  created transparent activity
and run work manager and on boot complete re-start trigger broadcast. To
start work manager again. Is this right approach.

Thanks for your time


Regards
Kiran S N

**Comment by krunalpatel3** [comment]
Hello Kiran

you are using periodic worker like this:-

mPeriodicWorkRequest = new PeriodicWorkRequest.Builder(MyPeriodicWork.class,
18, TimeUnit.MINUTES)
.addTag("periodicWorkRequest")
.build();

here every 18 MINUTES your backgound work will start.

**Comment by krunalpatel3** [comment]
do you want to run backgound task periodic?

**Comment by kiransnagaraj** [comment]
Based on event I have to send data to cloud by using workmanager. Event may
continuous like battery voltage or like network disconnect connection like
this

**Comment by krunalpatel3** [comment]
so the work manager should also run even if the battery is low and run when the device gets internet connection.

**Comment by krunalpatel3** [comment]
i think there will be no problem just to run work manager using transparent activity.

But if you are using PeriodicWorkRequest than you don't have to handle boot complete or restart or shutdown device it is automatically handle by WorkManager.When device get's reboot automatically  WorkManager schedule the your works.

**Comment by kiransnagaraj** [comment]
Ok I will take a look it and follow the same steps.  Thank you for your
time
